import type { Metadata } from "next";
import { Geist, Rubik } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";
import { TaskProvider } from "./context/TaskContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistRubik = Rubik({
  variable: "--font-Rubik",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <TaskProvider>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistRubik.className} antialiased `}
          >
            {children}
          </body>
        </html>
      </TaskProvider>
    </AuthProvider>
  );
}
